services:
  - type: web
    name: drivego
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: drivego-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
      

      services:
  - type: web
    name: drivego
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: python app.py
